{% set name = "docker-image-py" %}
{% set version = "0.1.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c0eebb6c25714b2a4f91a1462183e70252fa34fb189496d3c54711a64f12f96e
  # TODO: remove if/when merged https://github.com/realityone/docker-image-py/pull/8
  - fn: {{ name }}-{{ version }}-LICENSE-APACHE
    url: https://raw.githubusercontent.com/realityone/{{ name }}/{{ version }}/LICENSE
    sha256: b40930bbcf80744c86c46a12bc9da056641d722716c378f5659b9e555ef833e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - regex >=2019.4.14

test:
  imports:
    - docker_image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/realityone/docker-image-py
  summary: Parse docker image as distribution does.
  license: Apache-2.0
  license_file: {{ name }}-{{ version }}-LICENSE-APACHE

extra:
  recipe-maintainers:
    - bollwyvl
